# Generated by Django 4.0.3 on 2022-04-23 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Создано')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публиковать')),
            ],
        ),
        migrations.CreateModel(
            name='GroupC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Создано')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Название')),
                ('file', models.FileField(upload_to='homework/%Y/%m/%d', verbose_name='Домашка')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Создано')),
                ('curse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univer.curse')),
            ],
        ),
        migrations.AddField(
            model_name='curse',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univer.groupc'),
        ),
    ]
