# Generated by Django 4.0.3 on 2022-04-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curse',
            options={'ordering': ['-create_date'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='groupc',
            options={'ordering': ['-create_date'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-create_date'], 'verbose_name': 'Домашняя_задания', 'verbose_name_plural': 'Домашнии'},
        ),
        migrations.AddField(
            model_name='homework',
            name='author',
            field=models.CharField(default='None', max_length=25, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
